# Generated by Django 4.2.4 on 2023-08-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdj', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='adver',
        ),
    ]
